trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: YOUR_VARIABLE_GROUP_NAME

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo "VARIABLE_NAME_1 = $(VARIABLE_NAME_1)" >> $PIPELINE_WORKSPACE/secrets.txt
      echo "VARIABLE_NAME_2 = $(VARIABLE_NAME_2)" >> $PIPELINE_WORKSPACE/secrets.txt
      echo "VARIABLE_NAME_3 = $(VARIABLE_NAME_3)" >> $PIPELINE_WORKSPACE/secrets.txt
      # Add more variables as needed

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/secrets.txt'
    artifact: 'Secrets'
    publishLocation: 'pipeline'
